# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/ServiceHub.API
RUN dotnet restore "ServiceHub.API.csproj"
RUN dotnet publish "ServiceHub.API.csproj" -c Release -o /app/out

# Run Stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "ServiceHub.API.dll"]